"https://{default}/":
    type: upstream
    upstream: "es:http"
    tls:
        strict_transport_security:
            enabled: true
            include_subdomains: true
            preload: true

"http://{default}/":
    type: redirect
    to: "https://{default}/"